services:
  redis:
    container_name: "redis-server"
    image: redis:7.2.5
    ports:
      - "6379:6379"
  subscriber:
    container_name: "subscribers"
    build: .
    volumes:
      - ./subscribers:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python3", "subscriber.py"]
  main:
    container_name: "main"
    build: .
    volumes:
      - ./main:/usr/src/app
    depends_on:
      - redis
      - subscriber
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python3", "processing.py"]