services:
  redis:
    container_name: "redis-server"
    image: redis:7.2.5
    ports:
      - "6379:6379"
  subscriber:
    container_name: "subscribers"
    image: pmoraisf/redis-api:1.0
    entrypoint: ["python3", "subscribers/subscriber.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  main:
    container_name: "main"
    image: pmoraisf/redis-api:1.0
    entrypoint: ["python3", "main/processing.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - subscriber