apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: lucaschaga/main:latest
        name: main
        env:
        - name: REDIS_HOST
          value: "34.42.25.221"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 6379
          name: http
